export const GET_WEBNAME = "GET_WEBNAME";

export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const GET_WEBNAME_FAILURE = "GET_WEBNAME_FAILURE";
